config/routes.rb
BackToSchool::Application.routes.draw do

  get 'search' => 'search#index', as: 'search'
  get 'home/:id' => 'home#index', as: 'home'
  get 'home' => 'home#index'

  get "users/show"
  post "promotions/accept"
  post "promotions/leave"
  post "promotions/follow"

  root :to => "home#index"

  resources :promotions
  resources :events, only: :index

  resources :establishments do
    resources :promotions
  end

  resources :discussions do
    resources :messages, only: :create
    resources :events, only: :create
  end

  devise_for :users

  resources :users, only: :show

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  include Authority::Abilities
  self.authorizer_name = 'PromotionAuthorizer'

  belongs_to :establishment
  has_and_belongs_to_many :students, :class_name => 'User'
  has_many :followers
  has_many :users, through: :followers
  has_and_belongs_to_many :discussions

  validates :name, presence: true
  validates :establishment, presence: true
  validates :discussions, :length => {:minimum => 1}

  def get_discussion
    Discussion.joins([:promotions]).where('promotions.id = ?', self)
  end

  def get_accepted_followers
    User.joins([:followers]).where('followers.promotion_id = ?', self).where('followers.accepted = 1')
  end

  def get_all_users
    (get_accepted_followers + students).uniq
  end

  def accept(current_user, user)
    follower = nil
    followers.each do |f|
      if f.user == user
        follower = f
      end
    end
    if students.exists?(current_user) or get_accepted_followers.exists?(current_user) and !follower.nil? and !follower.accepted
      follower.accepted = true
      follower.save
    end
  end

  def leave(current_user)
    followers.each do |f|
      if f.user.id == current_user.id
        f.destroy
        break
      end
    end
  end

  def self.search(keyword, establishment)
    if keyword
      Promotion.joins([:establishment]).where('promotions.establishment_id = ?',establishment).where('promotions.name LIKE ?', "%#{keyword}%")
    else
      establishment.promotions
    end
  end
end

app/models/user.rb
class UserValidator < ActiveModel::Validator

  def validate(record)
    if record.est_admin == true && record.establishment == nil
      record.errors[:est_admin] << "Define an establishment if you want to grant establishement admin rights."
    end
    if record.student == true && record.professor == true
      record.errors[:est_admin] << "Not allowed to be student and professor at the same time."
    end
    if (record.student == true || record.professor == true) && record.promotions.count == 0
      record.errors[:promotions] << "Not allowed to create a professor or a student, without an associated promotion."
    end
  end
end


class User < ActiveRecord::Base
  devise :database_authenticatable,
         :rememberable, :validatable

  include Authority::UserAbilities
  include Authority::Abilities
  self.authorizer_name = 'UserAuthorizer'

  has_and_belongs_to_many :promotions
  belongs_to :establishment
  has_many :messages
  has_many :events
  has_many :followers
  has_many :follows_promotions, :class_name => 'Promotion', through: :followers
  has_and_belongs_to_many :discussions

  validates_presence_of :firstname, :message => "Firstname required."
  validates_presence_of :lastname, :message => "Lastname required."
  validates_length_of :email, :within => 6..100, :message => "E-Mail address length has to be minimum 6 characters.", :allow_blank => false
  validates :promotions, :length => { :minimum => 1 }
  validates_with UserValidator
  
  def get_default_promotion
    return promotions[0]
  end

  def get_complete_name
    firstname + " " + lastname
  end
  
  def get_all_discussions
    output = get_discussion_private + get_discussion_establishment
    get_discussion_promotion(output)
    output
  end

  def get_all_events
    events = []
    get_all_discussions.each do |d|
      events.concat(d.events)
    end
    events
  end

  def get_discussion_private
    Discussion.joins([:users]).where('users.id = ?', self)
  end

  def get_discussion_promotion(discussions)
    self.promotions.each do |promotion|
      discussions.concat(promotion.get_discussion)
    end
  end

  def get_discussion_establishment
    general_establishment.get_discussion
  end

  def accepted_followed_promotions
    Promotion.joins(:followers).where("followers.accepted = 1").where("followers.user_id = ?", self.id)
  end

  def accepted_followed_discussions
    Discussion.joins("INNER JOIN discussions_promotions ON discussions.id = discussions_promotions.discussion_id") \
              .joins("INNER JOIN promotions ON discussions_promotions.promotion_id = promotions.id") \
              .joins("INNER JOIN followers ON promotions.id = followers.promotion_id AND followers.accepted = true") \
              .where("followers.user_id = %s", self.id)
  end

  def promotions_discussions
    Discussion.joins("INNER JOIN discussions_promotions ON discussions.id = discussions_promotions.discussion_id") \
              .joins("INNER JOIN promotions ON discussions_promotions.promotion_id = promotions.id") \
              .joins("INNER JOIN promotions_users ON promotions.id = promotions_users.promotion_id") \
              .where("promotions_users.user_id = %s", self.id)
  end

  def general_establishment
    est = nil

    if establishment != nil
      est = establishment
    else
      est = promotions.first.establishment
    end

    est
  end

  def establishment_discussions
    Discussion.joins(:establishments).where("establishments.id = ?", self.general_establishment)
  end

  def discussion_participant?(discussion)
    discussions.include?(discussion) || promotions_discussions.include?(discussion) || accepted_followed_discussions.include?(discussion) || establishment_discussions.include?(discussion)
  end

  def user_is_in(promotion)
    o = false
    promotions.each do |p|
      if p.id == promotion.id
        o = true
        break
      end
    end
    unless o
      promotion.followers.each do |f|
        if f.user.id == id
          o = true
          break
        end
      end
    end
    o
  end

  def self.search(keyword, establishment)
    if keyword
      User.joins([:promotions]).where('promotions.establishment_id = ?', establishment).where('users.firstname LIKE ? OR users.lastname LIKE ?', "%#{keyword}%", "%#{keyword}%")
    else
      establishment.get_users
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  ensure_authorization_performed

  def show
    @user = User.find(params[:id])
    authorize_action_for(@user)


    @promotions = @user.promotions

    if @promotions.length <= 0
      raise ActionController::RoutingError.new('Not Found')
    end

    @establishment = current_user.get_default_promotion.establishment

    @followed_promotions = []
    @user.followers.each do |follow|
      @followed_promotions.append(follow.promotion)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_sidebar_user.html.erb
<div class="list-element">
  <%= link_to user.firstname + " " + user.lastname, user %>
  <% follow = (defined?(is_follower) and defined?(accepted) and !accepted and is_follower) ? "list-button accept-button" : "" %>

  <% unless !(defined?(can_email) and can_email) %>
      <% d = Discussion.new(users: [user]) %>
      <%= form_for(d) do |f| %>
          <% d.users.each do |user| %>
              <%= f.hidden_field :user_ids, :multiple => true, :value => user.id %>
          <% end %>
          <%= f.submit '', :class => ["list-button", "message-button"] %>
      <% end %>
  <% end %>

  <% unless follow.empty? %>
      <%= form_for(:promotion, :url => url_for(:controller => 'promotions', :action => 'accept')) do |f| %>
          <%= hidden_field_tag 'user', user.id %>
          <%= hidden_field_tag 'promotion', promotion.id %>
          <%= f.submit '', :class => follow %>
      <% end %>
  <% end %>

</div>

app/views/users/_user.html.erb
<article class="item list-element">
  <%= link_to user.firstname + " " + user.lastname, user %>
  <% if current_user.id != user.id %>
      <% d = Discussion.new(users: [user]) %>
      <%= form_for(d) do |f| %>
          <% d.users.each do |user| %>
              <%= f.hidden_field :user_ids, :multiple => true, :value => user.id %>
          <% end %>
          <%= f.submit '', :class => ["list-button", "message-button"] %>
      <% end %>
  <% end %>
</article>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>User Administration</h1>
<%= render @users %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, 'User | ' + @user.get_complete_name ) %>

<div id="content" class="col col9 last">
  <div id="discussion-list" class="row clearfix">
    <header><h2><%= @user.firstname %> <%= @user.lastname %> | <%= link_to @establishment.name, @establishment %></h2></header>

    <article class="list-title item">
      <p class="message">
        <strong>Promotions</strong>
      </p>
    </article>

  <% @promotions.each do |promotion| %>
      <article class="item list-element">
          <%= link_to promotion.name, promotion %>
          <% unless current_user.user_is_in(promotion) %>
              <%= form_for(:promotion, :url => url_for(:controller => 'promotions', :action => 'follow')) do |f| %>
                  <%= hidden_field_tag 'id', promotion.id %>
                  <%= f.submit '', :class => ["list-button", "message-button"] %>
              <% end %>
          <% end %>
      </article>
  <% end %>


    <article class="list-title item">
      <p class="message">
        <strong>Followed Promotions</strong>
      </p>
    </article>

  <% @followed_promotions.each do |promotion| %>
      <article class="item list-element">
          <%= link_to promotion.name, promotion %>
          <% unless current_user.user_is_in(promotion) %>
              <%= form_for(:promotion, :url => url_for(:controller => 'promotions', :action => 'follow')) do |f| %>
                  <%= hidden_field_tag 'id', promotion.id %>
                  <%= f.submit '', :class => ["list-button", "message-button"] %>
              <% end %>
          <% end %>
      </article>
  <% end %>
  </div>
</div>