config/routes.rb
BackToSchool::Application.routes.draw do

  get 'search' => 'search#index', as: 'search'
  get 'home/:id' => 'home#index', as: 'home'
  get 'home' => 'home#index'

  get "users/show"
  post "promotions/accept"
  post "promotions/leave"
  post "promotions/follow"

  root :to => "home#index"

  resources :promotions
  resources :events, only: :index

  resources :establishments do
    resources :promotions
  end

  resources :discussions do
    resources :messages, only: :create
    resources :events, only: :create
  end

  devise_for :users

  resources :users, only: :show

end

app/views/layouts/_footer.html.erb
<footer class="site-footer">
  <div class="col col12 first last"><p>© 2014 - M. Aeberli | D. Kühner | D. Antognini</p></div>
</footer>

app/views/layouts/_header.html.erb
<header id="site-header" class="row clearfix">
  <div id="logo" class="col col3 first"><h1><%= link_to('Back to school', root_path) %></h1></div>
  <!-- #logo -->
  <div id="user-action" class="col last">
    <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    <% end %>
  </div>
  <!-- #user-action -->
  <nav id="top-navigation" class="col">
    <ul>
      <% if user_signed_in? %>
          <li><%= link_to(current_user.general_establishment.name, current_user.general_establishment, class: params[:establishement] == 'events' ? 'active' : nil) %></li>
          <li><%= link_to('Discussions', discussions_path, class: params[:controller] == 'discussions' ? 'active' : nil) %></li>
          <li><%= link_to('Events', events_path, class: params[:controller] == 'events' ? 'active' : nil) %></li>
          <li><%= link_to('Search', search_path, class: params[:controller] == 'search' ? 'active' : nil) %></li>
      <% end %>
    </ul>
  </nav>
  <!-- #top-navigation -->
</header>

app/views/layouts/_iehacks.html.erb
<!--[if IE 8]>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js "></script>
<![endif]-->

app/views/layouts/_notifications.html.erb
<div>
  <!-- These paragraphe are very important (especially for the devise gem to inform the user) -->
  <% if notice %>
      <section class="notice flashbox" >
        <a href="#" class="right close">
          <%= image_tag("close-flashbox.png", :alt => "Close") %>
        </a>
        <p ><%= notice %></p>
      </section>
  <% end %>
  <% if alert %>
      <section class="alert flashbox" >
        <a href="#" class="right close">
          <%= image_tag("close-flashbox.png", :alt => "Close") %>
        </a>
        <p ><%= alert %></p>
      </section>
  <% end %>
</div>

app/views/layouts/_sidebar_discussion.erb
<div id="students-list-container" class="row">
  <header><h2>Participants</h2></header>
  <input type="checkbox" id="toggle-students" class="toogle"><label for="toggle-students"></label>

  <div class="content">
    <% participants.each do |student|%>
        <%= render :partial => '/users/sidebar_user', :object => student, as: 'user', locals: {:can_email => current_user.id != student.id} %>
    <% end %>
  </div>
</div>

<% if participants_follower.size > 0 %>
    <div id="followers-list-container" class="row">
      <header><h2>Followers</h2></header>
      <input type="checkbox" id="toggle-followers" class="toogle"><label for="toggle-followers"></label>
      <div class="content">
        <% participants_follower.each do |follower|%>
            <%= render :partial => '/users/sidebar_user', :object => follower.user, as: 'user', locals: {:is_follower => true, :accepted => follower.accepted, :can_email => current_user.id != follower.user.id, :promotion => promotion} %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/layouts/_sidebar_home.erb
<div id="promotions-list-container" class="row">
  <header><h2>Promotions</h2></header>
  <input type="checkbox" id="toggle-promotions" class="toogle"><label for="toggle-promotions"></label>

  <div class="content">
    <% promotions.each do |promotion| %>
        <%= render :partial => '/promotions/sidebar_promotion', :object => promotion, as: 'promotion', locals:{:selected_promotion => selected_promotion.id == promotion.id, :current_user => @current_user} %>
    <% end %>
    <% followed_promotions.each do |promotion| %>
        <%= render :partial => '/promotions/sidebar_promotion', :object => promotion, as: 'promotion', locals: {:selected_promotion => selected_promotion.id == promotion.id, :is_followed => true, :current_user => @current_user} %>
    <% end %>
  </div>
</div>

<div id="students-list-container" class="row">
  <header><h2>Students</h2></header>
  <input type="checkbox" id="toggle-students" class="toogle"><label for="toggle-students"></label>

  <div class="content">
    <% promotion_students.each do |student|%>
        <%= render :partial => '/users/sidebar_user', :object => student, as: 'user', locals: {:can_email => current_user.id != student.id, :current_user => @current_user} %>
    <% end %>
  </div>
</div>


<div id="followers-list-container" class="row">
  <header><h2>Followers</h2></header>
  <input type="checkbox" id="toggle-followers" class="toogle"><label for="toggle-followers"></label>
  <div class="content">
    <% promotion_followers.each do |follower|%>
        <%= render :partial => '/users/sidebar_user', :object => follower.user, as: 'user', locals: {:is_follower => true, :accepted => follower.accepted, :can_email => current_user.id != follower.user, :current_user => @current_user, :promotion => follower.promotion} %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/iehacks' %>
</head>
<body>
<div id="site-container" class="contentcenter clearfix">

  <%= render 'layouts/header' %>

  <main id="site-page" class="clearfix">
    <div id="content" class="col col9 last">

      <%= render 'layouts/notifications' %>

      <%= yield %>
    </div>
    <div id="sidebar" class="col col3 first"><%=yield :sidebar%></div><!-- Do not put this on multilines, or it breacks .col:empty -->
  </main>

  <%= render 'layouts/footer' %>

</div>
</body>
</html>